replicaCount: 2
image:
  repository: kamaldocker29/fastapi-cicd-demo
  tag: 0915fe9
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  path: /healthz
ingress:
  enabled: false
  className: nginx
  host: fastapi.example.com
