replicaCount: 2
image:
  repository: kamaldocker29/fastapi-cicd-demo
  tag: c181747
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
secondaryService:
  enabled: true
  replicaCount: 1
  nameSuffix: secondary
  serviceName: fastapi-secondary
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
probes:
  path: /healthz
metrics:
  path: /metrics
  serviceMonitor:
    enabled: true
ingress:
  enabled: false
  className: nginx
  host: fastapi.example.com
